name: enum_to_string
description: Better conversion of ENUMs to string. Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
version: 1.0.0

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
