name: logger
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
